-- MySQL Script generated by MySQL Workbench
-- Tue Oct 22 16:07:57 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema SalonKeeper
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SalonKeeper
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SalonKeeper` DEFAULT CHARACTER SET latin1 ;
USE `SalonKeeper` ;

-- -----------------------------------------------------
-- Table `SalonKeeper`.`appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SalonKeeper`.`appointments` (
  `appointmentId` INT(11) NOT NULL AUTO_INCREMENT,
  `stylistId` INT(11) NOT NULL,
  `serviceId` INT(11) NOT NULL,
  `clientId` INT(11) NOT NULL,
  `date` TEXT NOT NULL,
  `startTime` TEXT NOT NULL,
  `endTime` TEXT NOT NULL,
  `createdBy` INT(11) NULL DEFAULT NULL,
  `createDate` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`appointmentId`),
  UNIQUE INDEX `appointmentId_UNIQUE` (`appointmentId` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `SalonKeeper`.`clientInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SalonKeeper`.`clientInfo` (
  `clientID` INT(11) NOT NULL AUTO_INCREMENT,
  `firstName` TEXT NOT NULL,
  `lastName` TEXT NOT NULL,
  `address` TEXT NULL DEFAULT NULL,
  `phone` TEXT NOT NULL,
  `email` TEXT NULL DEFAULT NULL,
  `state` TEXT NOT NULL,
  `city` TEXT NOT NULL,
  `zip` INT(11) NOT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`clientID`),
  UNIQUE INDEX `clientID_UNIQUE` (`clientID` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `SalonKeeper`.`serviceSubTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SalonKeeper`.`serviceSubTypes` (
  `subTypeID` INT(11) NOT NULL AUTO_INCREMENT,
  `subTypeName` TEXT NULL DEFAULT NULL,
  `typeID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`subTypeID`),
  UNIQUE INDEX `subTypeID_UNIQUE` (`subTypeID` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `SalonKeeper`.`serviceTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SalonKeeper`.`serviceTypes` (
  `categoryId` INT(11) NOT NULL AUTO_INCREMENT,
  `typeName` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`categoryId`),
  UNIQUE INDEX `categoryId_UNIQUE` (`categoryId` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `SalonKeeper`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SalonKeeper`.`services` (
  `serviceID` INT(11) NOT NULL AUTO_INCREMENT,
  `serviceName` TEXT NULL DEFAULT NULL,
  `serviceType` INT(11) NULL DEFAULT NULL,
  `serviceSubType` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`serviceID`),
  UNIQUE INDEX `serviceID_UNIQUE` (`serviceID` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `SalonKeeper`.`stylist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SalonKeeper`.`stylist` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstName` TEXT NULL DEFAULT NULL,
  `lastName` TEXT NULL DEFAULT NULL,
  `title` INT(11) NULL DEFAULT NULL,
  `birthdate` TEXT NULL DEFAULT NULL,
  `password` TEXT NULL DEFAULT NULL,
  `active` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `SalonKeeper`.`stylistServices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SalonKeeper`.`stylistServices` (
  `entryId` INT(11) NOT NULL AUTO_INCREMENT,
  `stylistId` INT(11) NOT NULL,
  `serviceId` INT(11) NOT NULL,
  `offered` INT(11) NOT NULL,
  PRIMARY KEY (`entryId`),
  UNIQUE INDEX `entryId_UNIQUE` (`entryId` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 248
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
